export const migrations = [
`CREATE TABLE \`decks\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`remote_id\` text,
	\`name\` text NOT NULL,
	\`description\` text,
	\`subject\` text,
	\`chapter\` text,
	\`cover_image\` text,
	\`version\` integer DEFAULT 1,
	\`is_downloaded\` integer DEFAULT false,
	\`downloaded_at\` integer,
	\`is_premium\` integer DEFAULT false,
	\`user_id\` text,
	\`tags\` text DEFAULT '[]',
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE TABLE \`flashcards\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`deck_id\` text NOT NULL,
	\`front_content\` text NOT NULL,
	\`back_content\` text NOT NULL,
	\`media_urls\` text DEFAULT '[]',
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE TABLE \`reviews\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`flashcard_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`rating\` integer NOT NULL,
	\`reviewed_at\` integer NOT NULL,
	\`response_time_ms\` integer,
	\`previous_stability\` real,
	\`new_stability\` real,
	\`previous_difficulty\` real,
	\`new_difficulty\` real,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE TABLE \`rooms\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`code\` text NOT NULL,
	\`name\` text NOT NULL,
	\`description\` text,
	\`created_by\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE INDEX \`room_code_idx\` ON \`rooms\` (\`code\`);`,
`CREATE TABLE \`study_sessions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`deck_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`start_time\` integer NOT NULL,
	\`end_time\` integer,
	\`cards_studied\` integer DEFAULT 0,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE TABLE \`sync_queue\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`operation\` text NOT NULL,
	\`entity_type\` text NOT NULL,
	\`entity_id\` text NOT NULL,
	\`payload\` text NOT NULL,
	\`status\` text DEFAULT 'pending',
	\`retry_count\` integer DEFAULT 0,
	\`last_error\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);`,
`CREATE TABLE \`user_flashcard_status\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`flashcard_id\` text NOT NULL,
	\`interval\` integer DEFAULT 1,
	\`stability\` real DEFAULT 0,
	\`difficulty\` real DEFAULT 0,
	\`repetitions\` integer DEFAULT 0,
	\`due_date\` integer NOT NULL,
	\`last_reviewed\` integer,
	\`is_bookmarked\` integer DEFAULT false,
	\`notes\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`deleted_at\` integer
);`,
`CREATE INDEX \`due_date_idx\` ON \`user_flashcard_status\` (\`due_date\`);`,
`CREATE UNIQUE INDEX \`user_card_idx\` ON \`user_flashcard_status\` (\`user_id\`,\`flashcard_id\`);`
];
