// Mock Data for the Frontend Revamp

export const MOCK_USER_STATS = {
  name: "Arjun",
  streak: 12,
  today: {
    reviewsCompleted: 15,
    estimatedTimeMin: 8,
  },
  subjectMastery: [
    { subject: "Physics", percentage: 68 },
    { subject: "Chemistry", percentage: 42 },
    { subject: "Maths", percentage: 85 },
  ],
  activityTrend: [
    { day: "Mon", count: 120 },
    { day: "Tue", count: 85 },
    { day: "Wed", count: 40 },
    { day: "Thu", count: 150 },
    { day: "Fri", count: 200 },
    { day: "Sat", count: 50 },
    { day: "Sun", count: 180 },
  ],
  // 90 days of heatmap data (0-4 intensity)
  heatmap: Array.from({ length: 90 }).map(() => Math.floor(Math.random() * 5)),
};

export const MOCK_CURRICULUM = {
  Physics: {
    icon: "atom", // lucide icon name
    chapters: [
      { id: "p1", name: "Kinematics 1D", subtitle: "Motion, Graphs, Velocity", selected: false },
      { id: "p2", name: "Newton's Laws", subtitle: "Dynamics, Friction, Pulleys", selected: false },
      { id: "p3", name: "Work, Power & Energy", subtitle: "Conservation, Collisions", selected: false },
      { id: "p4", name: "Rotational Motion", subtitle: "Torque, Inertia, Rolling", selected: false },
      { id: "p5", name: "Gravitation", subtitle: "Fields, Potential, Orbits", selected: false },
    ]
  },
  Chem: {
    icon: "flask-conical",
    chapters: [
      { id: "c1", name: "Atomic Structure", subtitle: "Bohr Model, Quantum Numbers", selected: false },
      { id: "c2", name: "Chemical Bonding", subtitle: "VSEPR, MOT, Hybridization", selected: false },
      { id: "c3", name: "Thermodynamics", subtitle: "Enthalpy, Entropy, Gibbs", selected: false },
      { id: "c4", name: "Equilibrium", subtitle: "Le Chatelier, Ionic Equilibrium", selected: false },
      { id: "c5", name: "Organic Chemistry", subtitle: "IUPAC, Isomerism, GOC", selected: false },
    ]
  },
  Maths: {
    icon: "function-square", // approximation for math icon
    chapters: [
      { id: "m1", name: "Calculus", subtitle: "Limits, Continuity, Differentiability", selected: false },
      { id: "m2", name: "Algebra", subtitle: "Quadratic, Sequences, Binomial", selected: false },
      { id: "m3", name: "Coordinate Geometry", subtitle: "Straight Lines, Circles, Conics", selected: false },
      { id: "m4", name: "Trigonometry", subtitle: "Ratios, Identities, Equations", selected: false },
      { id: "m5", name: "Vectors & 3D", subtitle: "Dot Product, Cross Product, Planes", selected: false },
    ]
  }
};

export const MOCK_CONTENT_TYPES = [
  { id: "ct1", label: "Formulas", icon: "function-square", selected: false },
  { id: "ct2", label: "Concepts", icon: "lightbulb", selected: false },
  { id: "ct3", label: "Bookmarks", icon: "Bookmark", selected: false },
  { id: "ct4", label: "Mistakes", icon: "alert-circle", selected: false },
];

export const MOCK_TEMP_CARDS = [
  {
    id: "card-1-1",
    front: "State Newton's First Law of Motion",
    back: "An object at rest stays at rest, and an object in motion stays in motion with the same speed and direction, unless acted upon by an unbalanced force. This is also known as the Law of Inertia.",
    contentType: "text",
    tags: ["physics", "mechanics", "newton laws"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: ["https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?q=80&w=400&auto=format&fit=crop", "https://images.unsplash.com/photo-1614935151651-0bea6508db6b?q=80&w=400&auto=format&fit=crop"]
  },
  {
    id: "card-1-2",
    front: "What is the formula for the Time of Flight of a projectile?",
    back: "$T = \\frac{2u \\sin \\theta}{g}$\n\nwhere $u$ is initial velocity, $\\theta$ is the angle of projection, and $g$ is acceleration due to gravity.",
    contentType: "latex",
    tags: ["physics", "kinematics", "projectile motion"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-3",
    front: "Define the Work-Energy Theorem.",
    back: "The net work done on an object by all forces equals the change in its kinetic energy.\n\n$W_{net} = KE_f - KE_i = \\Delta KE$",
    contentType: "mixed",
    tags: ["physics", "mechanics", "work-energy"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-4",
    front: "What is the Principle of Conservation of Linear Momentum?",
    back: "If no external net force acts on a closed system of objects, the total linear momentum of the system remains constant through time.\n\n$P_i = P_f$",
    contentType: "text",
    tags: ["physics", "mechanics", "momentum"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-5",
    front: "What is the formula for the escape velocity of a planet?",
    back: "$v_e = \\sqrt{\\frac{2GM}{R}}$\n\nwhere $G$ is the gravitational constant, $M$ is the mass of the planet, and $R$ is its radius.",
    contentType: "latex",
    tags: ["physics", "gravitation", "escape velocity"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-6",
    front: "What is the relation between Torque ($\\tau$) and Angular Momentum ($L$)?",
    back: "The net external torque acting on a system is equal to the rate of change of its angular momentum:\n$\\tau = \\frac{dL}{dt}$",
    contentType: "latex",
    tags: ["physics", "mechanics", "rotational motion"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-7",
    front: "Define Hooke's Law for elastic materials.",
    back: "Within the elastic limit, the stress applied to a body is directly proportional to the strain produced:\n$Stress \\propto Strain \\Rightarrow \\sigma = E \\cdot \\epsilon$",
    contentType: "mixed",
    tags: ["physics", "properties of matter", "elasticity"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-8",
    front: "What is the formula for Terminal Velocity of a sphere in a viscous fluid?",
    back: "$v_t = \\frac{2r^2( \\rho - \\sigma )g}{9\\eta}$\n\nwhere $r$ is radius, $\\rho$ is density of sphere, $\\sigma$ is density of fluid, and $\\eta$ is coefficient of viscosity.",
    contentType: "latex",
    tags: ["physics", "fluid mechanics", "viscosity"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-9",
    front: "State Bernoulli's Principle equation.",
    back: "$P + \\frac{1}{2}\\rho v^2 + \\rho gh = \\text{constant}$\n\nIt expresses the conservation of energy for a flowing non-viscous fluid.",
    contentType: "latex",
    tags: ["physics", "fluid mechanics", "bernoulli"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-10",
    front: "What is the First Law of Thermodynamics?",
    back: "The heat energy supplied to a system ($\\Delta Q$) is equal to the sum of the increase in internal energy ($\\Delta U$) and the work done by the system ($\\Delta W$):\n$\\Delta Q = \\Delta U + \\Delta W$",
    contentType: "latex",
    tags: ["physics", "thermodynamics"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-11",
    front: "Define the Doppler Effect for sound waves.",
    back: "The apparent change in the frequency of a wave caused by relative motion between the source of the wave and the observer.",
    contentType: "text",
    tags: ["physics", "waves", "doppler effect"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-12",
    front: "What is the formula for the Time Period of a simple pendulum?",
    back: "$T = 2\\pi\\sqrt{\\frac{L}{g}}$\n\nwhere $L$ is the length of the string and $g$ is acceleration due to gravity.",
    contentType: "latex",
    tags: ["physics", "oscillations", "pendulum"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-13",
    front: "State Gauss's Law in Electrostatics.",
    back: "The total electric flux through a closed surface is equal to $1/\\epsilon_0$ times the net charge enclosed by the surface:\n$\\oint \\vec{E} \\cdot d\\vec{A} = \\frac{q_{enclosed}}{\\epsilon_0}$",
    contentType: "latex",
    tags: ["physics", "electrostatics", "gauss law"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-14",
    front: "What is the relation between Current ($I$) and Drift Velocity ($v_d$)?",
    back: "$I = nAe v_d$\n\nwhere $n$ is free electron density, $A$ is cross-sectional area, and $e$ is electronic charge.",
    contentType: "latex",
    tags: ["physics", "current electricity"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: "",
    mediaUrls: []
  },
  {
    id: "card-1-15",
    front: "State Lenz's Law of Electromagnetic Induction.",
    back: "The direction of an induced electromotive force (EMF) is such that it always opposes the change in magnetic flux that caused it.",
    contentType: "text",
    tags: ["physics", "emi", "lenz law"],
    deckId: "temp_deck",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    interval: 1,
    stability: 0,
    difficulty: 0,
    repetitions: 0,
    dueDate: Date.now(),
    lastReviewed: null,
    isBookmarked: false,
    notes: ""
  }
];
